// Example fleet for Dev Mode (SPINUP_DEV_MODE=1) — a small, deliberately varied set
// of servers/sites/events so every view has something interesting to show: an EOL
// Ubuntu server, EOL PHP versions, a Bedrock site, a non-WP app, an empty server, a
// disabled-HTTPS site, and a mix of disk usage / update counts. All domains are
// example.com/.org/.net — never a real client's.
//
// freshFixtures() returns a deep clone so MockSpinupWPClient can mutate its own copy
// freely without leaking state across StoreProvider remounts.

import type { Event, Server, Site } from "../api/types.ts"

const GB = 1024 * 1024 * 1024

const SERVERS: Server[] = [
  {
    id: 101,
    name: "web1.example.com",
    provider_name: "digitalocean",
    ubuntu_version: "24.04",
    ip_address: "203.0.113.11",
    ssh_port: 22,
    timezone: "UTC",
    region: "nyc3",
    size: "s-2vcpu-4gb",
    disk_space: { total: 80 * GB, available: 61 * GB, used: 19 * GB, updated_at: "2026-07-01T08:00:00Z" },
    database: null,
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    created_at: "2024-11-02T10:15:00Z",
    status: "active",
  },
  {
    id: 102,
    name: "web2.example.com",
    provider_name: "vultr",
    ubuntu_version: "22.04",
    ip_address: "203.0.113.12",
    ssh_port: 22,
    timezone: "UTC",
    region: "ewr",
    size: "vc2-2c-4gb",
    disk_space: { total: 60 * GB, available: 55 * GB, used: 5 * GB, updated_at: "2026-07-01T08:00:00Z" },
    database: null,
    connection_status: "connected",
    reboot_required: true,
    upgrade_required: false,
    created_at: "2026-06-20T14:00:00Z",
    status: "active",
  },
  {
    id: 103,
    name: "web3.example.org",
    provider_name: "hetzner",
    ubuntu_version: "20.04",
    ip_address: "203.0.113.13",
    ssh_port: 22,
    timezone: "UTC",
    region: "nbg1",
    size: "cx31",
    disk_space: { total: 40 * GB, available: 7 * GB, used: 33 * GB, updated_at: "2026-07-01T08:00:00Z" },
    database: null,
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: true,
    created_at: "2022-03-14T09:30:00Z",
    status: "active",
  },
  {
    id: 104,
    name: "web9.example.org",
    provider_name: "linode",
    ubuntu_version: "24.04",
    ip_address: "203.0.113.19",
    ssh_port: 22,
    timezone: "UTC",
    region: "us-east",
    size: "g6-standard-2",
    disk_space: { total: 80 * GB, available: 68 * GB, used: 12 * GB, updated_at: "2026-07-01T08:00:00Z" },
    database: null,
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    created_at: "2025-01-08T16:45:00Z",
    status: "active",
  },
]

const SITES: Site[] = [
  {
    id: 1001,
    server_id: 101,
    domain: "example.com",
    additional_domains: [{ id: 1, domain: "www.example.com", created_at: "2024-11-02T10:20:00Z" }],
    site_user: "example",
    php_version: "8.3",
    public_folder: "/",
    is_wordpress: true,
    page_cache: { enabled: true },
    https: { enabled: true },
    database: { id: 1, user_id: 1, table_prefix: "wp_" },
    backups: { files: true, database: true, retention_period: 14, next_run_time: "2026-07-03T03:00:00Z" },
    wp_core_update: false,
    wp_theme_updates: 1,
    wp_plugin_updates: 3,
    created_at: "2024-11-02T10:20:00Z",
    status: "active",
  },
  {
    id: 1002,
    server_id: 101,
    domain: "shop.example.com",
    site_user: "shop",
    php_version: "8.3",
    public_folder: "/web/",
    is_wordpress: true,
    page_cache: { enabled: true },
    https: { enabled: true },
    database: { id: 2, user_id: 2, table_prefix: "wp_" },
    backups: { files: true, database: true, retention_period: 14, next_run_time: "2026-07-03T03:00:00Z" },
    git: {
      repo: "git@github.com:example/shop-bedrock.git",
      branch: "main",
      deploy_script: "composer install -o --no-dev",
      push_enabled: true,
      deployment_url: null,
    },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    created_at: "2025-02-18T13:00:00Z",
    status: "active",
  },
  {
    id: 1003,
    server_id: 101,
    domain: "blog.example.com",
    site_user: "blog",
    php_version: "8.1",
    public_folder: "/",
    is_wordpress: true,
    page_cache: { enabled: false },
    https: { enabled: true },
    database: { id: 3, user_id: 3, table_prefix: "wp_" },
    backups: { files: true, database: true, retention_period: 7, next_run_time: "2026-07-03T03:00:00Z" },
    wp_core_update: true,
    wp_theme_updates: 2,
    wp_plugin_updates: 5,
    created_at: "2023-08-05T11:00:00Z",
    status: "active",
  },
  {
    id: 1004,
    server_id: 103,
    domain: "app.example.org",
    site_user: "app",
    php_version: "8.2",
    public_folder: "/public/",
    is_wordpress: false,
    https: { enabled: true },
    created_at: "2022-04-01T09:00:00Z",
    status: "active",
  },
  {
    id: 1005,
    server_id: 104,
    domain: "web9.example.org",
    site_user: "web9",
    php_version: "8.3",
    public_folder: "/",
    is_wordpress: false,
    https: { enabled: true },
    created_at: "2025-01-08T17:00:00Z",
    status: "active",
  },
  {
    id: 1006,
    server_id: 103,
    domain: "docs.example.org",
    site_user: "docs",
    php_version: "7.4",
    public_folder: "/",
    is_wordpress: true,
    page_cache: { enabled: false },
    https: { enabled: false },
    database: { id: 4, user_id: 4, table_prefix: "wp_" },
    backups: { files: false, database: false },
    wp_core_update: true,
    wp_theme_updates: 0,
    wp_plugin_updates: 8,
    created_at: "2022-06-11T15:20:00Z",
    status: "active",
  },
]

const EVENTS: Event[] = [
  {
    id: 9001,
    initiated_by: "dev-mode",
    server_id: 101,
    name: "site.php_version.updated",
    status: "deployed",
    output: "PHP updated to 8.3 for shop.example.com",
    created_at: "2026-06-30T09:00:00Z",
    started_at: "2026-06-30T09:00:05Z",
    finished_at: "2026-06-30T09:00:42Z",
  },
  {
    id: 9002,
    initiated_by: "dev-mode",
    server_id: 101,
    name: "site.cache.purged",
    status: "deployed",
    output: "Page cache and object cache purged for example.com",
    created_at: "2026-06-29T16:12:00Z",
    started_at: "2026-06-29T16:12:01Z",
    finished_at: "2026-06-29T16:12:09Z",
  },
  {
    id: 9003,
    initiated_by: "dev-mode",
    server_id: 103,
    name: "server.rebooted",
    status: "deployed",
    output: "Server rebooted successfully",
    created_at: "2026-06-27T04:00:00Z",
    started_at: "2026-06-27T04:00:02Z",
    finished_at: "2026-06-27T04:01:15Z",
  },
]

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T
}

export function freshFixtures(): { servers: Server[]; sites: Site[]; events: Event[] } {
  return { servers: clone(SERVERS), sites: clone(SITES), events: clone(EVENTS) }
}
